<template>
    <div class="update-log-editor-container">
        <a-page-header :title="isEdit ? '编辑更新日志' : '新增更新日志'" @back="handleBack">
            <template #extra>
                <a-space>
                    <a-button @click="handleBack">取消</a-button>
                    <a-button type="primary" @click="handleSave" :loading="saving">
                        保存草稿
                    </a-button>
                    <a-button type="primary" @click="handleSaveAndPublish" :loading="publishing">
                        保存并发布
                    </a-button>
                </a-space>
            </template>
        </a-page-header>

        <div class="editor-content">
            <a-form ref="formRef" :model="formData" :rules="rules" :label-col="{ span: 3 }" :wrapper-col="{ span: 18 }">
                <a-form-item label="版本号" name="version" required>
                    <a-input v-model:value="formData.version" placeholder="例如: v1.0.0" style="width: 300px" />
                    <div class="form-item-tip">请遵循语义化版本规范 (主版本.次版本.修订号)</div>
                </a-form-item>

                <a-form-item label="标题" name="title" required>
                    <a-input v-model:value="formData.title" placeholder="请输入更新日志标题" :maxlength="200" show-count />
                </a-form-item>

                <a-form-item label="更新类型" name="updateType" required>
                    <a-radio-group v-model:value="formData.updateType">
                        <a-radio value="feature">
                            <a-tag color="green">新功能</a-tag>
                        </a-radio>
                        <a-radio value="fix">
                            <a-tag color="orange">修复</a-tag>
                        </a-radio>
                        <a-radio value="optimize">
                            <a-tag color="blue">优化</a-tag>
                        </a-radio>
                        <a-radio value="breaking">
                            <a-tag color="red">重大变更</a-tag>
                        </a-radio>
                    </a-radio-group>
                </a-form-item>

                <a-form-item label="影响模块" name="affectedModules">
                    <a-select v-model:value="formData.affectedModules" mode="tags" placeholder="请选择或输入影响的模块"
                        style="width: 100%" :options="moduleOptions" />
                    <div class="form-item-tip">可以选择已有模块或输入新模块名称</div>
                </a-form-item>

                <a-form-item label="关联变更" name="relatedChangeId">
                    <a-input v-model:value="formData.relatedChangeId" placeholder="OpenSpec 变更 ID (可选)"
                        style="width: 400px" />
                    <div class="form-item-tip">如果此更新日志关联了 OpenSpec 变更,请填写变更 ID</div>
                </a-form-item>

                <a-form-item label="内容格式" name="contentType">
                    <a-radio-group v-model:value="formData.contentType">
                        <a-radio value="html">富文本 (HTML)</a-radio>
                        <a-radio value="markdown">Markdown</a-radio>
                    </a-radio-group>
                </a-form-item>

                <a-form-item label="更新内容" name="content" required>
                    <div class="editor-wrapper">
                        <!-- 富文本编辑器 -->
                        <div v-if="formData.contentType === 'html'" class="html-editor">
                            <RichTextEditor v-model="formData.content" :height="500" />
                        </div>

                        <!-- Markdown 编辑器 -->
                        <div v-else class="markdown-editor">
                            <a-tabs v-model:activeKey="markdownTab">
                                <a-tab-pane key="edit" tab="编辑">
                                    <a-textarea v-model:value="formData.content" placeholder="请输入 Markdown 格式的更新内容"
                                        :rows="20" style="font-family: 'Consolas', 'Monaco', monospace" />
                                </a-tab-pane>
                                <a-tab-pane key="preview" tab="预览">
                                    <div class="markdown-preview" v-html="markdownPreview"></div>
                                </a-tab-pane>
                            </a-tabs>
                        </div>
                    </div>
                    <div class="form-item-tip">
                        建议包含: 新增功能、优化改进、Bug 修复、注意事项等内容
                    </div>
                </a-form-item>

                <a-form-item label="自动生成设计文档" name="autoGenerateDesignDoc">
                    <a-switch v-model:checked="formData.autoGenerateDesignDoc" />
                    <span style="margin-left: 8px; color: #666">
                        发布时自动从关联的 OpenSpec 变更中生成功能设计文档
                    </span>
                </a-form-item>
            </a-form>
        </div>
    </div>
</template>

<script setup lang="ts">
    import { ref, reactive, computed, onMounted } from 'vue'
    import { useRouter, useRoute } from 'vue-router'
    import { message } from 'ant-design-vue'
    import type { UpdateLogFormData } from '@/types'
    import {
        getUpdateLogById,
        createUpdateLog,
        updateUpdateLog,
        publishUpdateLog
    } from '@/api/updateLog'
    import RichTextEditor from '@/components/RichTextEditor.vue'

    const router = useRouter()
    const route = useRoute()

    // 判断是否为编辑模式
    const isEdit = computed(() => !!route.params.id)
    const logId = computed(() => route.params.id as string)

    // 表单引用
    const formRef = ref()

    // 表单数据
    const formData = reactive < UpdateLogFormData & { autoGenerateDesignDoc?: boolean } > ({
        version: '',
        title: '',
        content: '',
        contentType: 'html',
        updateType: 'feature',
        affectedModules: [],
        relatedChangeId: '',
        autoGenerateDesignDoc: true
    })

    // Markdown 相关
    const markdownTab = ref('edit')
    const markdownPreview = computed(() => {
        // NOTE: 这里应该使用 markdown 解析库,暂时使用简单的 HTML 转换
        // TODO: 集成 marked 或 markdown-it 库
        return formData.content.replace(/\n/g, '<br>')
    })

    // 模块选项
    const moduleOptions = ref([
        { label: '质量检验', value: '质量检验' },
        { label: '供方管理', value: '供方管理' },
        { label: '系统管理', value: '系统管理' },
        { label: '数据应用', value: '数据应用' },
        { label: '权限管理', value: '权限管理' },
        { label: '流程管理', value: '流程管理' }
    ])

    // 表单验证规则
    const rules = {
        version: [
            { required: true, message: '请输入版本号', trigger: 'blur' },
            {
                pattern: /^v?\d+\.\d+\.\d+(-[a-zA-Z0-9]+)?$/,
                message: '版本号格式不正确,例如: v1.0.0 或 1.0.0',
                trigger: 'blur'
            }
        ],
        title: [
            { required: true, message: '请输入标题', trigger: 'blur' },
            { min: 5, max: 200, message: '标题长度应在 5-200 个字符之间', trigger: 'blur' }
        ],
        updateType: [
            { required: true, message: '请选择更新类型', trigger: 'change' }
        ],
        content: [
            { required: true, message: '请输入更新内容', trigger: 'blur' },
            { min: 10, message: '内容至少 10 个字符', trigger: 'blur' }
        ]
    }

    // 状态
    const saving = ref(false)
    const publishing = ref(false)

    // 加载数据
    const loadData = async () => {
        if (!isEdit.value) return

        try {
            const response = await getUpdateLogById(logId.value)
            if (response.success) {
                Object.assign(formData, response.data)
            } else {
                message.error(response.message)
                router.back()
            }
        } catch (error) {
            message.error('加载数据失败')
            console.error(error)
            router.back()
        }
    }

    // 保存
    const handleSave = async () => {
        try {
            await formRef.value.validate()
            saving.value = true

            const apiCall = isEdit.value
                ? updateUpdateLog(logId.value, formData)
                : createUpdateLog(formData)

            const response = await apiCall
            if (response.success) {
                message.success(isEdit.value ? '保存成功' : '创建成功')
                router.push('/system/update-log')
            } else {
                message.error(response.message)
            }
        } catch (error: any) {
            if (error.errorFields) {
                message.error('请检查表单填写是否正确')
            } else {
                message.error('保存失败')
                console.error(error)
            }
        } finally {
            saving.value = false
        }
    }

    // 保存并发布
    const handleSaveAndPublish = async () => {
        try {
            await formRef.value.validate()
            publishing.value = true

            // 先保存
            const apiCall = isEdit.value
                ? updateUpdateLog(logId.value, formData)
                : createUpdateLog(formData)

            const saveResponse = await apiCall
            if (!saveResponse.success) {
                message.error(saveResponse.message)
                return
            }

            // 再发布
            const publishResponse = await publishUpdateLog(saveResponse.data.id)
            if (publishResponse.success) {
                message.success('发布成功')
                router.push('/system/update-log')
            } else {
                message.error(publishResponse.message)
            }
        } catch (error: any) {
            if (error.errorFields) {
                message.error('请检查表单填写是否正确')
            } else {
                message.error('发布失败')
                console.error(error)
            }
        } finally {
            publishing.value = false
        }
    }

    // 返回
    const handleBack = () => {
        router.back()
    }

    // 初始化
    onMounted(() => {
        loadData()
    })
</script>

<style scoped>
    .update-log-editor-container {
        background: #fff;
        min-height: calc(100vh - 104px);
    }

    .editor-content {
        padding: 24px;
        max-width: 1400px;
        margin: 0 auto;
    }

    .form-item-tip {
        margin-top: 4px;
        color: #999;
        font-size: 12px;
    }

    .editor-wrapper {
        width: 100%;
    }

    .html-editor {
        width: 100%;
    }

    .editor-container {
        min-height: 400px;
    }

    .markdown-editor {
        width: 100%;
    }

    .markdown-preview {
        min-height: 400px;
        padding: 16px;
        border: 1px solid #d9d9d9;
        border-radius: 4px;
        background: #fafafa;
        line-height: 1.8;
    }

    :deep(.ant-page-header) {
        border-bottom: 1px solid #f0f0f0;
        padding: 16px 24px;
    }
</style>